my_shop_admin:
    resource: "@MyShopAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

my_shop_default:
    resource: "@MyShopDefaultBundle/Resources/config/routing.yml"
    prefix:   /

logout:
     path:  logout

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
