<?php

namespace MyShop\DefaultBundle\Repository;

/**
 * IconPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
