my_shop_admin.index:
    path:   /
    defaults: { _controller: MyShopAdminBundle:Default:index }

my_shop_admin.product_add:
    path:   /product/add
    defaults: { _controller: MyShopAdminBundle:Product:add }

my_shop_admin.product_list:
    path:   /product/list/{page}/{perPage}
    defaults: { _controller: MyShopAdminBundle:Product:list, page: 1 , perPage: 9}
    requirements:
            page: \d+
            perPage: \d+

my_shop_admin.product_list_by_category:
    path:   /category/{id_category}/product/list
    defaults: { _controller: MyShopAdminBundle:Product:listByCategory }
    requirements:
        id_category: \d+

my_shop_admin.product_delete:
    path:   /product/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Product:delete }
    requirements:
        id: \d+

my_shop_admin.product_edit:
    path:   /product/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Product:edit }
    requirements:
        id: \d+

my_shop_admin.category_add:
    path:   /category/add/{idParent}
    defaults: { _controller: MyShopAdminBundle:Category:add, idParent:null }

my_shop_admin.manufacturer_add:
    path:   /manufacturer/add
    defaults: { _controller: MyShopAdminBundle:Manufacturer:add }

my_shop_admin.manufacturer_edit:
    path:   /manufacturer/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Manufacturer:edit }
    requirements:
            id: \d+

my_shop_admin.manufacturer_delete:
    path:   /manufacturer/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Manufacturer:delete }
    requirements:
            id: \d+

myshop_admin.manufacturer_list:
    path:   /manufacturer/list
    defaults: { _controller: MyShopAdminBundle:Manufacturer:list }

my_shop_admin.product_photo_add:
    path:   /product/{idProduct}/photo/add
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:add }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_list:
    path:   /product/{idProduct}/photos
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:list }
    requirements:
        idProduct: \d+

my_shop_admin.product_photo_edit:
    path:   /product/{id}/photo/edit
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:edit }
    requirements:
          id: \d+

my_shop_admin.product_photo_delete:
    path:   /product/{id}/photo/delete
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:delete }
    requirements:
                id: \d+

my_shop_admin.product_delete_ajax:
    path:   /product/{id}/delete/ajax
    defaults: { _controller: MyShopAdminBundle:Product:deleteAjax }
    requirements:
         id: \d+
    options:
         expose: true

my_shop_admin.category_list:
    path:   /category/list/{idParentCategory}
    defaults: { _controller: MyShopAdminBundle:Category:list, idParentCategory:null }

my_shop_admin.tree:
    path:   /category/tree 
    defaults: { _controller: MyShopAdminBundle:Category:tree }

my_shop_admin.category_edit:
    path:   /category/{id}/edit
    defaults: { _controller: MyShopAdminBundle:Category:edit  }
    requirements:
            id: \d+

my_shop_admin.category_delete:
    path:   /category/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Category:delete }
    requirements:
            id: \d+

login:
    path:   /login
    defaults: { _controller: MyShopAdminBundle:Login:login }

my_shop_admin.sendmail:
    path:   /product/photo/{id}/sendmail
    defaults: { _controller: MyShopAdminBundle:ProductPhoto:sendMail }
    requirements:
            id: \d+

my_shop_admin.user_add:
    path:   /user/add
    defaults: { _controller: MyShopAdminBundle:User:add }

my_shop_admin.user_edit:
    path:   /user/{id}/edit
    defaults: { _controller: MyShopAdminBundle:User:edit }
    requirements:
            id: \d+

my_shop_admin.user_delete:
    path:   /user/{id}/delete
    defaults: { _controller: MyShopAdminBundle:User:delete }
    requirements:
            id: \d+

my_shop_admin.user_list:
    path:   /user/list
    defaults: { _controller: MyShopAdminBundle:User:userList }

my_shop_admin.demo_user_load:
    path:   /load/user
    defaults: { _controller: MyShopAdminBundle:Default:loadUser }

my_shop_admin.demo_product_load:
    path:   /load/product
    defaults: { _controller: MyShopAdminBundle:Default:loadProduct }

my_shop_admin.demo_category_load:
    path:   /load/category
    defaults: { _controller: MyShopAdminBundle:Default:loadCategory }

my_shop_admin.import_csv_file:
    path:  /import/csv
    defaults: {_controller:  MyShopAdminBundle:LoadingProduct:importProducts}

my_shop_admin.export_csv_file:
    path:  /export/csv
    defaults: {_controller:  MyShopAdminBundle:LoadingProduct:exportProduct}

my_shop_admin.page_list:
    path: /page/list
    defaults: {_controller: MyShopAdminBundle:Page:index }

my_shop_admin.page_add:
    path: /page/add
    defaults: {_controller: MyShopAdminBundle:Page:add }

my_shop_admin.page_edit:
    path: /page/edit/{id}
    defaults: {_controller: MyShopAdminBundle:Page:edit }
    requirements:
            id: \d+

my_shop_admin.page_delete:
    path: /page/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Page:delete }
    requirements:
            id: \d+            

myshop_admin.upload_image:
    path: /upload_image
    defaults: {_controller: MyShopAdminBundle:Default:uploadImage }

my_shop_admin.info_add:
    path: /info/add
    defaults: {_controller: MyShopAdminBundle:InformationAboutShop:add }

my_shop_admin.info_list:
    path: /info/list
    defaults: {_controller: MyShopAdminBundle:InformationAboutShop:list }

my_shop_admin.info_edit:
    path: /info/edit/{id}
    defaults: {_controller: MyShopAdminBundle:InformationAboutShop:edit }

my_shop_admin.info_delete:
    path: /info/{id}/delete
    defaults: { _controller: MyShopAdminBundle:InformationAboutShop:delete }
    requirements:
            id: \d+

my_shop_admin.comment_add:
    path: /comment/add
    defaults: {_controller: MyShopAdminBundle:Comments:add }

my_shop_admin.comments_list:
    path: /comment/list
    defaults: {_controller: MyShopAdminBundle:Comments:list }

my_shop_admin.comment_edit:
    path: /comment/edit/{id}
    defaults: {_controller: MyShopAdminBundle:Comments:edit }

my_shop_admin.comment_delete:
    path: /comment/{id}/delete
    defaults: { _controller: MyShopAdminBundle:Comments:delete }
    requirements:
            id: \d+

myshop_admin.ajaxrequest:
     path: /test
     defaults: {_controller: MyShopAdminBundle:Default:test }



