services:
    myshop_admin.my_exception_listener:
        class: MyShop\AdminBundle\Event\MyExceptionListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception}

    myshop_admin.product_subscriber:
        class: MyShop\AdminBundle\Event\ProductSubscriber
        tags:
            - { name: kernel.event_listener, event: product_add_event, method: onProductAddEvent}
    
    myshop_admin.check_img:
        class: MyShop\AdminBundle\ImageCheck\CheckImg
        parent: "myshop_admin.base_check"
     
    myshop_admin.base_check:
        class: MyShop\AdminBundle\ImageCheck\BaseCheck
        abstract: true
        arguments:
             - "%upload_image_type_list%"         

    myshop_admin.image_name_generator:
        class: MyShop\AdminBundle\ImageCheck\GenerateName

    myshop_admin.resize_img:
            class: MyShop\AdminBundle\ImageCheck\ResizeImage
            arguments:
                - "%upload_image_size_list%"

    myshop_admin.image_uploader:
         class:  MyShop\AdminBundle\ImageCheck\UploadImageService
         arguments:
            - "@myshop_admin.check_img"
            - "@myshop_admin.image_name_generator"
            - "@myshop_admin.resize_img"
         calls:
            - ["setUploadImageRootDir", ["%image_upload_dir%"]]


    myshop_admin.twig_custom_extension_greeting:
        class: MyShop\AdminBundle\Twig\Extension
        public: false  
        tags:
            - { name: twig.extension }

    myshop_admin.mail_sender:
        class: MyShop\AdminBundle\ImageCheck\MailSender
        arguments:
           - "@mailer"

    myshop_admin.photo_remover:
         class:  MyShop\AdminBundle\ImageCheck\PhotoRemover
         arguments:
            - "@doctrine.orm.default_entity_manager"
            - "%image_upload_dir%"

    myshop_admin.product_import_export:
          class:   MyShop\AdminBundle\Utils\ProductImportExport
          arguments:
             - "@doctrine.orm.entity_manager"
             - "@kernel"
             - "@event_dispatcher"
        

 

