my_shop.product_info:
    path: /product/{id}
    defaults: { _controller: MyShopDefaultBundle:Default:showProduct }
    methods: [GET]
    requirements:
        id: \d+

myshop.product_list:
    path: /product/list
    defaults: { _controller: MyShopDefaultBundle:Default:showProductList }

myshop.product_create:
    path: /product/create
    defaults: { _controller: MyShopDefaultBundle:Default:createProduct }

myshop.api.product_details:
    path:   /api/rest/product/{id}.json
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:productDetails }

myshop.api.product_details_xml:
    path:   /api/rest/product/{id}.xml
    defaults: { _controller: MyShopDefaultBundle:API/REST/Product:productDetailsXML }

myshop.api.json_rpc:
    path:   /api/jsonrpc
    defaults: { _controller: MyShopDefaultBundle:API/JsonRPC/JsonRPC:index }

myshop.index_page:
    path: /
    defaults: { _controller: MyShopDefaultBundle:Default:index }

myshop.curl_client_json:
    path: /client/jsonrpc/{idProduct}
    defaults: { _controller: MyShopDefaultBundle:Default:clientCurl}
    requirements:
        idProduct: \d+

myshop.page:
    path: /{pageKey}
    defaults: { _controller: MyShopDefaultBundle:Page:index }

myshop.navigation:
    path: /navigation
    defaults: { _controller: MyShopDefaultBundle:Default:list }