<?php

namespace MyShop\AdminBundle\Repository;

/**
 * InformationAboutShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationAboutShopRepository extends \Doctrine\ORM\EntityRepository
{
}
